/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sqlin' at '2/21/17 8:29 PM' with Gradle 3.1
 *
 * @author sqlin, @date 2/21/17 8:29 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
